apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 5m
  path: "./istio-controlplane"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
