apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  path: "./kyverno"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
