apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: "./monitoring"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
