apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        resources:
          limits:
            cpu: 1500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          type: NodePort
          ports:
          - name: status-port
            port: 15021
            protocol: TCP
            targetPort: 15021
            nodePort: 32021
          - name: http2
            port: 80
            protocol: TCP
            targetPort: 8080
            nodePort: 32080 
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
            nodePort: 32443 
          - name: tcp-istiod
            port: 15012
            protocol: TCP
            targetPort: 15012                      
            nodePort: 32012
          - name: tls
            port: 15443
            protocol: TCP
            targetPort: 15443
            nodePort: 32543
          - name: tcp-amq
            nodePort: 32400
            port: 32400
            protocol: TCP
            targetPort: 32400
          - name: tcp-generic-0
            nodePort: 32401
            port: 32401
            protocol: TCP
            targetPort: 32401
          - name: tcp-generic-1
            nodePort: 32402
            port: 32402
            protocol: TCP
            targetPort: 32402
          - name: tcp-generic-2
            nodePort: 32403
            port: 32403
            protocol: TCP
            targetPort: 32403 
    istiodRemote:
      enabled: false
    pilot:
      enabled: true
      k8s:
  hub: docker.io/istio
  profile: default
  meshConfig:
    enablePrometheusMerge: true
  tag: 1.9.2
  values:
    global:
      imagePullPolicy: "IfNotPresent"
      logging:
        level: default:info
